env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode12.2
      script:
        - set -o pipefail
        - swift test
        - swift run tribute list
